import { componentRegistry } from './ComponentRegistry';
import type { ComponentMetadata } from '../metadata/ComponentMetadata';

const BUILT_IN_COMPONENTS: ComponentMetadata[] = [
  {
    id: 'Rectangle',
    displayName: 'Rectangle',
    description: 'Basic rectangular shape',
    category: 'basic',
    icon: 'square',
    keywords: ['shape', 'box', 'rect'],
    defaultWidth: 100,
    defaultHeight: 100,
    minimumWidth: 1,
    minimumHeight: 1,
    supportsChildren: false,
    supportsText: false,
    supportsImage: false,
    supportsLayout: false,
    supportsRotation: true,
    supportsEffects: true,
  },
  {
    id: 'Group',
    displayName: 'Group',
    description: 'A transparent container for grouping nodes',
    category: 'layout',
    icon: 'folder',
    keywords: ['group', 'folder', 'container'],
    defaultWidth: 100,
    defaultHeight: 100,
    minimumWidth: 1,
    minimumHeight: 1,
    supportsChildren: true,
    supportsText: false,
    supportsImage: false,
    supportsLayout: true,
    supportsRotation: true,
    supportsEffects: true,
  },
  {
    id: 'Circle',
    displayName: 'Circle',
    description: 'Basic circular shape',
    category: 'basic',
    icon: 'circle',
    keywords: ['shape', 'round'],
    defaultWidth: 100,
    defaultHeight: 100,
    minimumWidth: 1,
    minimumHeight: 1,
    supportsChildren: false,
    supportsText: false,
    supportsImage: false,
    supportsLayout: false,
    supportsRotation: true,
    supportsEffects: true,
  },
  {
    id: 'Button',
    displayName: 'Button',
    description: 'Interactive button component',
    category: 'input',
    icon: 'mouse-pointer-click',
    keywords: ['button', 'click', 'interactive'],
    defaultWidth: 120,
    defaultHeight: 44,
    minimumWidth: 40,
    minimumHeight: 24,
    supportsChildren: false,
    supportsText: true,
    supportsImage: false,
    supportsLayout: false,
    supportsRotation: true,
    supportsEffects: true,
  },
  {
    id: 'Text',
    displayName: 'Text',
    description: 'Basic text block',
    category: 'typography',
    icon: 'type',
    keywords: ['text', 'font', 'typography', 'label'],
    defaultWidth: 200,
    defaultHeight: 50,
    minimumWidth: 10,
    minimumHeight: 10,
    supportsChildren: false,
    supportsText: true,
    supportsImage: false,
    supportsLayout: false,
    supportsRotation: true,
    supportsEffects: true,
  },
  {
    id: 'Card',
    displayName: 'Card',
    description: 'Versatile card container',
    category: 'cards',
    icon: 'panel-top',
    keywords: ['card', 'container', 'box', 'panel'],
    defaultWidth: 300,
    defaultHeight: 200,
    minimumWidth: 50,
    minimumHeight: 50,
    supportsChildren: true,
    supportsText: false,
    supportsImage: false,
    supportsLayout: true,
    supportsRotation: true,
    supportsEffects: true,
  },
  {
    id: 'Container',
    displayName: 'Container',
    description: 'Basic layout container',
    category: 'layout',
    icon: 'box',
    keywords: ['container', 'layout', 'wrap', 'group'],
    defaultWidth: 400,
    defaultHeight: 300,
    minimumWidth: 10,
    minimumHeight: 10,
    supportsChildren: true,
    supportsText: false,
    supportsImage: false,
    supportsLayout: true,
    supportsRotation: true,
    supportsEffects: true,
  },
  {
    id: 'Image',
    displayName: 'Image',
    description: 'Image placeholder or element',
    category: 'media',
    icon: 'image',
    keywords: ['image', 'picture', 'photo', 'img', 'media'],
    defaultWidth: 200,
    defaultHeight: 200,
    minimumWidth: 10,
    minimumHeight: 10,
    supportsChildren: false,
    supportsText: false,
    supportsImage: true,
    supportsLayout: false,
    supportsRotation: true,
    supportsEffects: true,
  }
];

export function registerDefaultComponents() {
  BUILT_IN_COMPONENTS.forEach(comp => componentRegistry.registerComponent(comp));
}
