import type { FrameworkAdapter } from '../FrameworkAdapter';
import type { GeneratorContext } from '../GeneratorContext';
import type { GeneratedFile } from '../../CompilerContext';

export class FlutterGenerator implements FrameworkAdapter {
  public id = 'adapter_flutter';
  public name = 'Flutter Mobile (Dart)';
  public targetFramework = 'flutter';

  public supportsLanguage(lang: string): boolean {
    return lang === 'dart';
  }

  public generateProject(context: GeneratorContext): GeneratedFile[] {
    const ir = context.ir;
    const files: GeneratedFile[] = [];

    files.push({
      path: 'pubspec.yaml',
      type: 'markdown',
      content: `name: ${ir.metadata.name.toLowerCase().replace(/\s+/g, '_')}
description: "Generated by VisualStack Studio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true`,
    });

    files.push({
      path: 'lib/main.dart',
      type: 'dart',
      content: `import 'package:flutter/material.dart';

void main() {
  runApp(const VisualStackApp());
}

class VisualStackApp extends StatelessWidget {
  const VisualStackApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${ir.metadata.name}',
      theme: ThemeData.dark(),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('${ir.metadata.name}')),
      body: const Center(
        child: Text('VisualStack Flutter Application', style: TextStyle(fontSize: 20)),
      ),
    );
  }
}`,
    });

    return files;
  }
}
