import type { NodeDefinition } from './NodeDefinition';

export const DATABASE_NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: 'db_find_many',
    category: 'Database',
    name: 'Find Records',
    description: 'Queries multiple database records matching filters, sorting, and pagination.',
    icon: 'database',
    color: '#06b6d4',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'table', name: 'Table/Collection', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'filter', name: 'Filter (Object)', type: 'data', dataType: 'object', color: '#f59e0b' },
      { id: 'sort', name: 'Sort By', type: 'data', dataType: 'object', color: '#f59e0b' },
      { id: 'limit', name: 'Limit', type: 'data', dataType: 'number', color: '#3b82f6' },
      { id: 'offset', name: 'Offset', type: 'data', dataType: 'number', color: '#3b82f6' },
    ],
    outputs: [
      { id: 'success', name: 'Success', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'error', name: 'Error', type: 'execution', dataType: 'execution', color: '#ef4444' },
      { id: 'records', name: 'Records', type: 'data', dataType: 'array', color: '#a855f7' },
      { id: 'count', name: 'Count', type: 'data', dataType: 'number', color: '#3b82f6' },
    ],
    defaultConfig: { table: 'users', limit: 20, offset: 0 },
  },
  {
    type: 'db_find_by_id',
    category: 'Database',
    name: 'Find Record By ID',
    description: 'Retrieves a single database record by primary key or ID.',
    icon: 'search',
    color: '#06b6d4',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'table', name: 'Table', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'id', name: 'Record ID', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    outputs: [
      { id: 'found', name: 'Found', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'not_found', name: 'Not Found', type: 'execution', dataType: 'execution', color: '#ef4444' },
      { id: 'record', name: 'Record', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    defaultConfig: { table: 'users' },
  },
  {
    type: 'db_insert_one',
    category: 'Database',
    name: 'Insert Record',
    description: 'Creates a new record in the database.',
    icon: 'plus-circle',
    color: '#06b6d4',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'table', name: 'Table', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'data', name: 'Record Data', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    outputs: [
      { id: 'success', name: 'Success', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'error', name: 'Error', type: 'execution', dataType: 'execution', color: '#ef4444' },
      { id: 'record', name: 'Created Record', type: 'data', dataType: 'object', color: '#f59e0b' },
      { id: 'insertedId', name: 'Inserted ID', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    defaultConfig: { table: '' },
  },
  {
    type: 'db_update_by_id',
    category: 'Database',
    name: 'Update Record',
    description: 'Updates fields on an existing database record by ID.',
    icon: 'edit-3',
    color: '#06b6d4',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'table', name: 'Table', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'id', name: 'Record ID', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'changes', name: 'Changes (Object)', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    outputs: [
      { id: 'success', name: 'Success', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'error', name: 'Error', type: 'execution', dataType: 'execution', color: '#ef4444' },
      { id: 'updatedRecord', name: 'Updated Record', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    defaultConfig: { table: '' },
  },
  {
    type: 'db_delete_by_id',
    category: 'Database',
    name: 'Delete Record',
    description: 'Deletes a database record by ID.',
    icon: 'trash-2',
    color: '#ef4444',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'table', name: 'Table', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'id', name: 'Record ID', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    outputs: [
      { id: 'success', name: 'Success', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'error', name: 'Error', type: 'execution', dataType: 'execution', color: '#ef4444' },
    ],
    defaultConfig: { table: '' },
  },
  {
    type: 'db_upsert',
    category: 'Database',
    name: 'Upsert Record',
    description: 'Inserts a new record if it does not exist, or updates it if found.',
    icon: 'refresh-cw',
    color: '#06b6d4',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'table', name: 'Table', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'conflictTarget', name: 'Unique Column', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'data', name: 'Data', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    outputs: [
      { id: 'success', name: 'Success', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'record', name: 'Record', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    defaultConfig: { table: '', conflictTarget: 'id' },
  },
  {
    type: 'db_count',
    category: 'Database',
    name: 'Count Records',
    description: 'Counts the number of records matching filter criteria.',
    icon: 'hash',
    color: '#06b6d4',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'table', name: 'Table', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'filter', name: 'Filter', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution' },
      { id: 'count', name: 'Count', type: 'data', dataType: 'number', color: '#3b82f6' },
    ],
    defaultConfig: { table: '' },
  },
  {
    type: 'db_aggregate',
    category: 'Database',
    name: 'Aggregate Data',
    description: 'Calculates SUM, AVG, MIN, MAX over a field.',
    icon: 'pie-chart',
    color: '#06b6d4',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'table', name: 'Table', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'field', name: 'Field', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution' },
      { id: 'result', name: 'Result', type: 'data', dataType: 'number', color: '#3b82f6' },
    ],
    defaultConfig: { table: '', field: 'amount', operation: 'SUM' },
  },
  {
    type: 'db_raw_query',
    category: 'Database',
    name: 'Raw SQL / Query',
    description: 'Executes a raw SQL statement or database query with parameters.',
    icon: 'terminal',
    color: '#64748b',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'sql', name: 'SQL Query', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'params', name: 'Params (Array)', type: 'data', dataType: 'array', color: '#a855f7' },
    ],
    outputs: [
      { id: 'success', name: 'Success', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'error', name: 'Error', type: 'execution', dataType: 'execution', color: '#ef4444' },
      { id: 'rows', name: 'Rows', type: 'data', dataType: 'array', color: '#a855f7' },
    ],
    defaultConfig: { sql: 'SELECT * FROM users WHERE active = $1' },
  },
  {
    type: 'db_transaction',
    category: 'Database',
    name: 'Database Transaction',
    description: 'Wraps database operations inside an atomic ACID transaction.',
    icon: 'layers',
    color: '#06b6d4',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
    ],
    outputs: [
      { id: 'tx_body', name: 'Transaction Body', type: 'execution', dataType: 'execution', color: '#f59e0b' },
      { id: 'commit', name: 'Committed', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'rollback', name: 'Rolled Back', type: 'execution', dataType: 'execution', color: '#ef4444' },
    ],
    defaultConfig: {},
  },
];
