import type { NodeDefinition } from './NodeDefinition';

export const ECOMMERCE_NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: 'stripe_checkout',
    category: 'E-Commerce',
    name: 'Stripe Checkout',
    description: 'Creates a Stripe Checkout session URL for one-time or subscription payments.',
    icon: 'credit-card',
    color: '#635bff',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'lineItems', name: 'Line Items (Array)', type: 'data', dataType: 'array', color: '#a855f7' },
      { id: 'successUrl', name: 'Success URL', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'cancelUrl', name: 'Cancel URL', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'customerEmail', name: 'Customer Email', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    outputs: [
      { id: 'success', name: 'Success', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'error', name: 'Error', type: 'execution', dataType: 'execution', color: '#ef4444' },
      { id: 'checkoutUrl', name: 'Checkout URL', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'sessionId', name: 'Session ID', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    defaultConfig: { mode: 'payment', currency: 'usd' },
  },
  {
    type: 'stripe_webhook',
    category: 'E-Commerce',
    name: 'Stripe Webhook Handler',
    description: 'Validates & parses incoming Stripe payment webhooks.',
    icon: 'bell',
    color: '#635bff',
    inputs: [],
    outputs: [
      { id: 'payment_succeeded', name: 'Payment Succeeded', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'payment_failed', name: 'Payment Failed', type: 'execution', dataType: 'execution', color: '#ef4444' },
      { id: 'sub_created', name: 'Subscription Created', type: 'execution', dataType: 'execution', color: '#3b82f6' },
      { id: 'eventData', name: 'Event Payload', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    defaultConfig: { webhookSecret: '' },
  },
  {
    type: 'stripe_subscription',
    category: 'E-Commerce',
    name: 'Manage Subscription',
    description: 'Creates or updates a recurring Stripe billing subscription.',
    icon: 'repeat',
    color: '#635bff',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'customerId', name: 'Customer ID', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'priceId', name: 'Price ID', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    outputs: [
      { id: 'success', name: 'Success', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'subscriptionId', name: 'Subscription ID', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    defaultConfig: { action: 'create' },
  },
  {
    type: 'cart_add_item',
    category: 'E-Commerce',
    name: 'Add to Cart',
    description: 'Adds an item or increments quantity in the shopping cart.',
    icon: 'shopping-cart',
    color: '#10b981',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'productId', name: 'Product ID', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'quantity', name: 'Quantity', type: 'data', dataType: 'number', color: '#3b82f6' },
      { id: 'price', name: 'Price', type: 'data', dataType: 'number', color: '#3b82f6' },
    ],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution' },
      { id: 'cart', name: 'Updated Cart', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    defaultConfig: { quantity: 1 },
  },
  {
    type: 'cart_remove_item',
    category: 'E-Commerce',
    name: 'Remove Cart Item',
    description: 'Removes an item from the cart by product ID.',
    icon: 'shopping-bag',
    color: '#ef4444',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'productId', name: 'Product ID', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution' },
      { id: 'cart', name: 'Updated Cart', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    defaultConfig: {},
  },
  {
    type: 'cart_calculate_total',
    category: 'E-Commerce',
    name: 'Calculate Cart Total',
    description: 'Calculates cart subtotal, discount, tax, and total amount.',
    icon: 'calculator',
    color: '#10b981',
    inputs: [
      { id: 'cart', name: 'Cart Object', type: 'data', dataType: 'object', color: '#f59e0b' },
      { id: 'taxRate', name: 'Tax Rate (%)', type: 'data', dataType: 'number', color: '#3b82f6' },
      { id: 'discountCode', name: 'Coupon Code', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    outputs: [
      { id: 'subtotal', name: 'Subtotal', type: 'data', dataType: 'number', color: '#3b82f6' },
      { id: 'tax', name: 'Tax', type: 'data', dataType: 'number', color: '#3b82f6' },
      { id: 'discount', name: 'Discount Amount', type: 'data', dataType: 'number', color: '#3b82f6' },
      { id: 'total', name: 'Total', type: 'data', dataType: 'number', color: '#3b82f6' },
    ],
    defaultConfig: { taxRate: 0 },
  },
  {
    type: 'order_create',
    category: 'E-Commerce',
    name: 'Create Order',
    description: 'Generates a new order record in database with order items.',
    icon: 'package',
    color: '#f59e0b',
    inputs: [
      { id: 'exec', name: 'Execute', type: 'execution', dataType: 'execution' },
      { id: 'userId', name: 'User ID', type: 'data', dataType: 'string', color: '#10b981' },
      { id: 'items', name: 'Order Items', type: 'data', dataType: 'array', color: '#a855f7' },
      { id: 'total', name: 'Total Amount', type: 'data', dataType: 'number', color: '#3b82f6' },
    ],
    outputs: [
      { id: 'success', name: 'Success', type: 'execution', dataType: 'execution', color: '#10b981' },
      { id: 'orderId', name: 'Order ID', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    defaultConfig: {},
  },
];
