import type { NodeDefinition } from './NodeDefinition';

export const EVENT_NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: 'event_app_started',
    category: 'Events',
    name: 'App Started',
    description: 'Entry point: fires once when the application initializes.',
    icon: 'zap',
    color: '#f59e0b',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
    ],
    defaultConfig: { eventName: 'app_started' },
    docs: 'Use as the root trigger for app-wide initialization logic.',
  },
  {
    type: 'event_page_loaded',
    category: 'Events',
    name: 'Page Loaded',
    description: 'Fires when a page/screen finishes loading.',
    icon: 'layout',
    color: '#6366f1',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
    ],
    defaultConfig: { eventName: 'page_loaded', screenId: '' },
  },
  {
    type: 'event_button_click',
    category: 'Events',
    name: 'Button Clicked',
    description: 'Fires when a specified button element is clicked.',
    icon: 'mouse-pointer',
    color: '#3b82f6',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
      { id: 'target', name: 'Target', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    defaultConfig: { eventName: 'button_click', elementId: '' },
  },
  {
    type: 'event_input_changed',
    category: 'Events',
    name: 'Input Changed',
    description: 'Fires when an input element value changes.',
    icon: 'edit-3',
    color: '#10b981',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
      { id: 'value', name: 'Value', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    defaultConfig: { eventName: 'input_changed', elementId: '' },
  },
  {
    type: 'event_form_submitted',
    category: 'Events',
    name: 'Form Submitted',
    description: 'Fires when a form is submitted.',
    icon: 'send',
    color: '#8b5cf6',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
      { id: 'data', name: 'Form Data', type: 'data', dataType: 'object', color: '#f59e0b' },
    ],
    defaultConfig: { eventName: 'form_submitted', formId: '' },
  },
  {
    type: 'event_hover',
    category: 'Events',
    name: 'Hover',
    description: 'Fires when the cursor enters an element.',
    icon: 'move',
    color: '#ec4899',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
      { id: 'target', name: 'Target', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    defaultConfig: { eventName: 'hover', elementId: '' },
  },
  {
    type: 'event_double_click',
    category: 'Events',
    name: 'Double Click',
    description: 'Fires on double-click of an element.',
    icon: 'mouse-pointer-2',
    color: '#f97316',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
      { id: 'target', name: 'Target', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    defaultConfig: { eventName: 'double_click', elementId: '' },
  },
  {
    type: 'event_scroll',
    category: 'Events',
    name: 'Scroll',
    description: 'Fires on page or element scroll.',
    icon: 'scroll',
    color: '#14b8a6',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
      { id: 'scrollX', name: 'Scroll X', type: 'data', dataType: 'number', color: '#3b82f6' },
      { id: 'scrollY', name: 'Scroll Y', type: 'data', dataType: 'number', color: '#3b82f6' },
    ],
    defaultConfig: { eventName: 'scroll', elementId: '' },
  },
  {
    type: 'event_timer',
    category: 'Events',
    name: 'Timer',
    description: 'Fires repeatedly or once after a configurable delay (ms).',
    icon: 'clock',
    color: '#a855f7',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
      { id: 'elapsed', name: 'Elapsed (ms)', type: 'data', dataType: 'number', color: '#3b82f6' },
    ],
    defaultConfig: { eventName: 'timer', delay: 1000, repeat: false },
  },
  {
    type: 'event_screen_open',
    category: 'Events',
    name: 'Screen Opened',
    description: 'Fires when a screen or modal is opened.',
    icon: 'monitor',
    color: '#0ea5e9',
    inputs: [],
    outputs: [
      { id: 'exec', name: 'Then', type: 'execution', dataType: 'execution', color: '#ffffff' },
      { id: 'screenId', name: 'Screen ID', type: 'data', dataType: 'string', color: '#10b981' },
    ],
    defaultConfig: { eventName: 'screen_open', screenId: '' },
  },
];
